### ISSUE TITLE
Reflection usage

### ISSUE THREAD

**Issue by pafelin** [atrauzzi/domain-tool#1]
Hey

I think the tool is handy but performance wise it should be improved. The problem is the heavy [usage](https://github.com/atrauzzi/domain-tool/blob/master/src/Service.php#L35) of the reflection class. ( saw it on a few other places as well )

Here is some [benchmark I found](http://stackoverflow.com/questions/294582/php-5-reflection-api-performance) but from personal experience I think it is even slower from what this benchmark is showing. 

Using the reflection class is really handy but in this scenario would lead to performance issues since through the whole application the create method would be used many times. That means hundreds or thousands of times per request the reflection class has to be instantiated. 

A possible solution to fix this is configuration or convention.

(maybe I am all wrong :) )

**Comment by atrauzzi** [comment]
Yeah, the reflection stuff is definitely expensive.  One issue is that relying on configuration makes the library heavier to use.

Minimum configuration was definitely one of its goals.

**Comment by atrauzzi** [comment]
@pafelin - If you like the library and want to make any improvements, feel free! :)
